export default [{
    title: 'Flex',
    description: '布局',
    icon: 'https://os.alipayobjects.com/rmsportal/zFqYaBWIPpYYORq.png',
    module: require('./components/flex/flex')
  },
  {
    title: 'Text',
    description: '文本展示',
    icon: 'https://os.alipayobjects.com/rmsportal/PfzuWlDVfndrQUK.png',
    module: require('./components/text/text')
  },
  {
    title: 'Image',
    description: '图片展示',
    icon: 'https://os.alipayobjects.com/rmsportal/NDsSvklLUeodsHK.png',
    module: require('./components/image/image')
  },
  {
    title: 'Input',
    description: '文本输入',
    icon: 'https://os.alipayobjects.com/rmsportal/SdSqpihcSBoBrFO.png',
    module: require('./components/input/input'),
  },
  {
    title: 'TextAreaItem',
    description: '多行输入',
    icon: 'https://os.alipayobjects.com/rmsportal/PfzuWlDVfndrQUK.png',
    module: require('./components/textareaitem/textareaitem'),
  },
  {
    title: 'ActivityIndicator',
    description: '活动指示器',
    icon: 'https://zos.alipayobjects.com/rmsportal/yVtRfZGoDxXObTK.png',
    module: require('./components/activityindicator/activityindicator'),
  },
  {
    title: 'Progress',
    description: '进度条',
    icon: 'https://os.alipayobjects.com/rmsportal/ihijukOXDlqXvPS.png',
    module: require('./components/progress/progress'),
  },
  {
    title: 'List',
    description: '列表',
    icon: 'https://os.alipayobjects.com/rmsportal/tiapjpdKPQGHhnC.png',
    module: require('./components/list/list'),
  },
  {
    title: 'FlatList',
    description: '长列表',
    icon: 'https://os.alipayobjects.com/rmsportal/tiapjpdKPQGHhnC.png',
    module: require('./components/FlatList/FlatList'),
  },
  {
    title: 'GridList',
    description: '网格列表',
    icon: 'https://os.alipayobjects.com/rmsportal/UBGcnLKfVQIXgUb.png',
    module: require('./components/grid/grid'),
  },
  {
    title: 'Card',
    description: '卡片',
    icon: 'https://os.alipayobjects.com/rmsportal/daARhPjKcxlSuuZ.png',
    module: require('./components/card/card'),
  }, {
    title: 'Checkbox',
    description: '复选框',
    icon: 'https://os.alipayobjects.com/rmsportal/dWPGltvdjaanrRd.png',
    module: require('./components/checkbox/checkbox'),
  },
  {
    title: 'ActionSheet',
    description: '动作面板',
    icon: 'https://zos.alipayobjects.com/rmsportal/cYmaBafYBnAxCqQ.png',
    module: require('./components/actionsheet/actionsheet'),
  },
  {
    title: 'Popover',
    description: '气泡',
    icon: 'https://os.alipayobjects.com/rmsportal/iIOLFHTKUCxBgUV.png',
    module: require('./components/popover/popover'),
  },
  {
    title: 'SegmentedControl',
    description: '分段器',
    icon: 'https://zos.alipayobjects.com/rmsportal/qCqRFuSbewqIWyv.png',
    module: require('./components/segmentedcontrol/segmentedcontrol'),
  }, {
    title: 'Switch',
    description: '滑动开关',
    icon: 'https://os.alipayobjects.com/rmsportal/ITFdMlELFchsTmz.png',
    module: require('./components/switch/switch'),
  },
  {
    title: 'Toast',
    description: '轻提示',
    icon: 'https://os.alipayobjects.com/rmsportal/nREwETegxvDndJZ.png',
    module: require('./components/toast/toast'),
  }, {
    title: 'Modal',
    description: '对话框',
    icon: 'https://os.alipayobjects.com/rmsportal/HzRRcuwtqUCCOBg.png',
    module: require('./components/modal/modal'),
  },
  {
    title: 'Carousel',
    description: '走马灯',
    icon: 'https://os.alipayobjects.com/rmsportal/FbIGJuDaiQoKNvj.png',
    module: require('./components/carousel/carousel'),
  },
  {
    title: 'SearchBar',
    description: '搜索栏',
    icon: 'https://os.alipayobjects.com/rmsportal/QnAmpSwlfPzjpSL.png',
    module: require('./components/searchbar/searchbar'),
  },
  {
    title: 'Badge',
    description: '徽标数',
    icon: 'https://os.alipayobjects.com/rmsportal/UwUpBYPYnlwVicM.png',
    module: require('./components/badge/badge'),
  },
  {
    title: 'RefreshControl',
    description: '下拉刷新',
    icon: 'https://os.alipayobjects.com/rmsportal/HzRRcuwtqUCCOBg.png',
    module: require('./components/refreshrontrol/refreshrontrol'),
  }, {
    title: 'SwipeAction',
    description: '滑动或长按操作',
    icon: 'https://os.alipayobjects.com/rmsportal/nlDYwTsLwJdnaKc.png',
    module: require('./components/swipeaction/swipeaction'),
  },
  {
    title: 'TabBar',
    description: '标签栏',
    icon: 'https://zos.alipayobjects.com/rmsportal/OZInMeAaDCHtaJU.png',
    module: require('./components/tabbar/tabbar'),
  }, {
    title: 'Tabs',
    description: '标签页',
    icon: 'https://os.alipayobjects.com/rmsportal/stWeDgdtEIKoiTU.png',
    module: require('./components/tabs/tabs'),
  },
  {
    title: 'Picker',
    description: '选择器',
    icon: 'https://os.alipayobjects.com/rmsportal/STBLvEutBwPySbL.png',
    module: require('./components/picker/picker'),
  }, 
  {
    title: 'PickerView',
    description: '选择器视图',
    icon: 'https://os.alipayobjects.com/rmsportal/STBLvEutBwPySbL.png',
    module: require('./components/pickerview/pickerview'),
  }, {
    title: 'DatePicker', 
    description: '日期选择',
    icon: 'https://os.alipayobjects.com/rmsportal/IQtMSWmYwLEuqln.png',
    module: require('./components/datepicker/datepicker'),
  }, {
    title: 'DatePickerView', 
    description: '日期选择视图',
    icon: 'https://os.alipayobjects.com/rmsportal/IQtMSWmYwLEuqln.png',
    module: require('./components/datepickerview/datepickerview'),
  },
  {
    title: 'ImagePicker',
    description: '图片选择',
    icon: 'https://os.alipayobjects.com/rmsportal/NDsSvklLUeodsHK.png',
    module: require('./components/imagepicker/imagepicker'),
  },
  {
    title: 'Camera',
    description: '拍照',
    icon: 'https://os.alipayobjects.com/rmsportal/NDsSvklLUeodsHK.png',
    module: require('./components/camera/camera'),
  },
];